version: '3.3'
services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Chisinau
    volumes:
      - $HOME/dvolumes/nextcloud/config:/config
      - $HOME/dvolumes/nextcloud/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=6eTb1aNo
      - TZ=Europe/Chisinau
    volumes:
      - $HOME/dvolumes/mariadb/config:/config
    restart: unless-stopped
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    ports:
      - '81:8181'
      - '80:8080'
      - '443:4443'
    volumes:
      - '$HOME/dvolumes/nginx-proxy-manager:/config'
    restart: unless-stopped
    image: jlesage/nginx-proxy-manager

  duckdns:
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Chisinau
      - SUBDOMAINS=needsrat
      - TOKEN=5e92a67f-ab8c-40bd-862a-7f09df804b00
    restart: unless-stopped
    image: linuxserver/duckdns:latest