#Homelab Config
version: '3.3'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${PATH}/nextcloud/config:/config
      - ${PATH}/nextcloud/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${PATH}/mariadb/config:/config
    restart: unless-stopped

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    ports:
      - '81:8181'
      - '80:8080'
      - '443:4443'
    volumes:
      - '${PATH}/nginx-proxy-manager:/config'
    restart: unless-stopped
    image: jlesage/nginx-proxy-manager

  duckdns:
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
    restart: unless-stopped
    image: linuxserver/duckdns:latest

networks:
  default:
      external:
          name: proxy