version: "3.3"

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ~/docker_volumes/nextcloud-config:/config
      - ~/docker_volumes/nextcloud-data:/data
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ~/docker_volumes/nextcloud-mariadb:/config
    restart: unless-stopped

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    volumes:
      - ~/docker_volumes/nginx-proxy-manager:/data
      - ~/docker_volumes/nginx-proxy-manager-le:/etc/letsencrypt
    restart: unless-stopped
    image: jc21/nginx-proxy-manager:latest

  duckdns:
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
    restart: unless-stopped
    image: linuxserver/duckdns:latest