#Homelab Config
version: "3.3"

services:
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ~/docker_volumes/nextcloud-config:/config
      - ~/docker_volumes/nextcloud-data:/data
    depends_on:
      - nextcloud-mariadb
    restart: unless-stopped

  nextcloud-mariadb:
    image: linuxserver/mariadb
    container_name: nextcloud-mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ~/docker_volumes/nextcloud-mariadb:/config
    restart: unless-stopped

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    volumes:
      - ~/docker_volumes/nginx-proxy-manager:/data
      - ~/docker_volumes/nginx-proxy-manager-le:/etc/letsencrypt
    restart: unless-stopped
    image: jc21/nginx-proxy-manager:latest

  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - CLI_ARGS= #optional
    volumes:
      - ~/docker_volumes/duplicati-config:/config
      - ~/docker_volumes/duplicati-backups:/backups
      - /:/source
    ports:
      - 8200:8200
    restart: unless-stopped

  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "67:67/udp"
  #     - "8080:80/tcp"
  #   environment:
  #     - TZ=${TZ}
  #     - WEBPASSWORD=6eTb1aNo
  #   # Volumes store your data between container upgrades
  #   volumes:
  #     - ~/docker_volumes/etc-pihole/:/etc/pihole/
  #     - ~/docker_volumes/etc-dnsmasq.d/:/etc/dnsmasq.d/
  #   # Recommended but not required (DHCP needs NET_ADMIN)
  #   #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped

#  duckdns:
#    container_name: duckdns
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=${TZ}
#      - SUBDOMAINS=${SUBDOMAINS}
#      - TOKEN=${TOKEN}
#    restart: unless-stopped
#    image: linuxserver/duckdns:latest

networks:
  default:
    name: proxy
