#Homelab Config
version: "3.3"

services:
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /var/lib/docker/dvolumes/nextcloud-config:/config
      - /var/lib/docker/dvolumes/nextcloud-data:/data
    depends_on:
      - nextcloud-mariadb
    restart: unless-stopped

  nextcloud-mariadb:
    image: linuxserver/mariadb
    container_name: nextcloud-mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - /var/lib/docker/dvolumes/nextcloud-mariadb:/config
    restart: unless-stopped

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    volumes:
      - /var/lib/docker/dvolumes/nginx-proxy-manager:/data
      - /var/lib/docker/dvolumes/nginx-proxy-manager-le:/etc/letsencrypt
    restart: unless-stopped
    image: jc21/nginx-proxy-manager:latest

  duckdns:
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
    restart: unless-stopped
    image: linuxserver/duckdns:latest

networks:
  default:
    name: proxy
